[project]
name = "onnxdiff"
version = "0.1.3"
description = "Diff your ONNXs"
readme = "README.md"
authors = [{ name = "yuxuan-z", email = "yuxuan-z19@qq.com" }]
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "grakel>=0.1.10",
    "numpy>=2.3.2",
    "onnx>=1.18.0",
    "onnxruntime>=1.22.1",
    "onnxscript>=0.3.2",
    "onnxsim>=0.4.36",
    "tabulate>=0.9.0",
]

[project.scripts]
onnxdiff = "onnxdiff.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.4.1"]
